### ISSUE TITLE
Streaming STT

### ISSUE THREAD

**Issue by ipernjakovic** [naudor/rhasspy_Google_STT#1]
Hi,

first of all, this repo helped me a lot, so thank you. 
Secondly, do you have any idea how would we implement google cloud streaming STT into rhasspy, because non-streaming one is just too slow for everyday use, at least for me. i had to switch to mycroft just because they have streaming STT out of the box and it works flawlessly.

Thanks!

**Comment by naudor** [comment]
Hi @ipernjakovic,

Very happy that the repo are usefull for you.
I'm not sure that Rhasspy are ready to use straming service but would be a good start point modifiying the code in GCloudSpeech/google-stt.py file with the code in [Google example](https://github.com/googleapis/python-speech/blob/HEAD/samples/microphone/transcribe_streaming_mic.py)
Sorry I didn't try it before then I can't help you better now.

Let me know if you get it

Thanks.
